-- 删除之前的普通索引
ALTER TABLE `TB_WZY_BLOG_USER`
    DROP INDEX `IDX_TB_WZY_BLOG_USER_NAME`,
    DROP INDEX `IDX_TB_WZY_BLOG_USER_PHONE`,
    DROP INDEX `IDX_TB_WZY_BLOG_USER_EMAIL`;

 -- 创建新的唯一索引
ALTER TABLE `TB_WZY_BLOG_USER`
    ADD UNIQUE INDEX `UK_TB_WZY_BLOG_USER_NAME`  (`name`),
    ADD UNIQUE INDEX `UK_TB_WZY_BLOG_USER_PHONE` (`phone`),
    ADD UNIQUE INDEX `UK_TB_WZY_BLOG_USER_EMAIL` (`email`);