mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

logging:
  level:
    com.wzy: DEBUG # 根日志级别
    com.baomidou.mybatisplus.extension.handlers: DEBUG

rocketmq:
  name-server: ${ROCKET_MQ_SERVER_DEV}
  consumer:
    group: ["article-pv-consumer-group"]

wenziyue:
  # wenziyue-uid-starter
  uid:
    step: 10
    prepare-next-percent: 70
  # wenziyue-security-starter
  security:
    expire: 43200 # token过期时间，测试12小时
    refresh-before-expiration: 3600  # 刷新token时间，测试1小时

# swagger-ui 配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: /v3/api-docs          # 明确告诉 UI 去这里拿接口定义

