mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

logging:
  level:
    com.wzy: DEBUG # 根日志级别

wenziyue:
  # wenziyue-uid-starter
  uid:
    step: 50
    prepare-next-percent: 70